app:
  name: GinCraft
  mode: debug  # debug, release, test
  port: 8080
  read_timeout: 60
  write_timeout: 60

log:
  level: debug  # debug, info, warn, error, fatal, panic
  filename: logs/app.log
  max_size: 100  # MB
  max_age: 30    # days
  max_backups: 10
  compress: false

mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: goframe
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # seconds

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10